jenkinsci/gradle-plugin

src/main/java/hudson/plugins/gradle/Gradle.java, src/main/resources/hudson/plugins/gradle/Gradle/config.jelly, src/main/resources/hudson/plugins/gradle/Gradle/help-passAsProperties.html
As of version 1.24 of the Gradle plugin, all job parameters are passed as JVM system properties via '-D'. This change keeps the default behaviour, but allows to pass job parameters via regular Gradle properties, i.e. '-P' so that they are immediately available in the Gradle DSL.
To pick one or the other, the job config GUI contains an additional checkbox with a corresponding help text (as of now, in english only).
Fixes JENKINS-17523, JENKINS-17523
=> [JENKINS-17523] feat: Enable passing job parameter as properties

src/main/resources/hudson/plugins/gradle/GradleTaskNote/DescriptorImpl/outline.jelly, src/main/resources/hudson/plugins/gradle/GradleTaskNote/script.js, src/main/resources/hudson/plugins/gradle/GradleTaskNote/style.css
JENKINS-26287 Prevent the console-outline block to overlap the console output in case of long task paths.
Add stylesheet and unorder list element for console-outline table  to
prevent it overlapping the console output in case of long task paths.
=> JENKINS-26287 Prevent the console-outline to overlap the console output

src/main/java/hudson/plugins/gradle/Gradle.java, src/main/resources/hudson/plugins/gradle/Gradle/config.jelly, src/main/resources/hudson/plugins/gradle/Gradle/help-wrapperScript.html
JENKINS-12769 Provide location of gradlew script, which required moving code into
radioBlocks which don't have inline, so I had to move to a POJO to store
them. Uses macro replacement on wrapper location.
=> JENKINS-12769 Provide location of gradlew script

build.gradle, src/main/java/hudson/plugins/gradle/Gradle.java, src/main/java/hudson/plugins/gradle/GradleInstallation.java
Specifically added them to the Descriptors.
cc @reviewbybees
=> [FIXED JENKINS-37394] Add @Symbol annotations for step and tool.

src/test/groovy/hudson/plugins/gradle/GradleInstallationRule.groovy, src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy
[JENKINS-42847](https://issues.jenkins-ci.org/browse/JENKINS-42847)
Include automated test for _get-gradle_ CLI command, which allows to gather the configured Gradle installations.
@reviewbybees @wolfs
=> [JENKINS-42847] Include automated test for CLI command

src/main/java/hudson/plugins/gradle/Gradle.java, src/main/resources/hudson/plugins/gradle/Gradle/config.jelly, src/test/groovy/hudson/plugins/gradle/CompatibilityTest.groovy, src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy, src/test/resources/hudson/plugins/gradle/CompatibilityTest/read_configuration_files_older_than_1_27/config.xml, src/test/resources/hudson/plugins/gradle/CompatibilityTest/read_configuration_files_older_than_1_27/hudson.plugins.gradle.Gradle.xml, src/test/resources/hudson/plugins/gradle/CompatibilityTest/read_configuration_files_older_than_1_27/jobs/old/config.xml
By default, not all parameters are passed as
properties. The old behavior can be enabled
again.
=> Add two new fields to pass properties

build.gradle, config/codenarc/codenarc.xml, src/main/java/hudson/plugins/gradle/GetGradleCommand.java, src/test/groovy/hudson/plugins/gradle/GradleInstallationRule.groovy, src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/GradleTaskNoteTest.java, src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy
[JENKINS-44126](https://issues.jenkins-ci.org/browse/JENKINS-44126)
Findbugs and animal-sniffer analyses are really useful for development.
- Execute animal sniffer when building.
- Execute Findbugs when building.
- Fix Findbugs errors.
@reviewbybees @wolfs
=> [JENKINS-44126] Include animal-sniffer and findbugs

src/main/java/hudson/plugins/gradle/Gradle.java, src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy
By utilizing the EnvVars.overrideAll(Map) method, it internally removes keys where the value is null or an empty string. This results in those parameters not being rewritten to empty properties as expected and the properties instead have the jenkins replacement string in them instead.
[FIXES JENKINS-45300]
=> Don't remove empty build vars

build.gradle
In order to meet the [prerequisites](https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Prerequisites) of plugin hosting in the Jenkins Organization, I'm adding the licensing definition in the Maven project.
@reviewbybees, What do you think?
=> Added a licensing definition to the Maven project

build.gradle, gradle/jcascTest.gradle, src/main/java/hudson/plugins/gradle/GradleInstallation.java, src/test/groovy/hudson/plugins/gradle/ConfigurationAsCodeTest.groovy, src/test/groovy/hudson/plugins/gradle/GradleInstallationRule.groovy, src/test/resources/hudson/plugins/gradle/ConfigurationAsCodeTest/configuration-as-code.yml
This fixes problems with JCasC for configuration import & export.
Also see the respective issue in JCasC - jenkinsci/configuration-as-code-plugin/issues/460.
=> [JENKINS-53575] Configuration-as-Code compatibility

src/main/java/hudson/plugins/gradle/BuildScanAction.java, src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy
This PR adds the appropriate annotations to `BuildScanAction` so that this information is available via the Jenkins REST APIs. This allows clients that hit the API to also get access to build scans published by a given Job w/o having to manually parse the console log.
=> Expose build scan action via Jenkins API

build.gradle, src/main/java/hudson/plugins/gradle/BuildScanAction.java, src/main/java/hudson/plugins/gradle/BuildScanLogScanner.java, src/main/java/hudson/plugins/gradle/BuildScanPublisher.java, src/main/java/hudson/plugins/gradle/GradleConsoleAnnotator.java, src/main/resources/hudson/plugins/gradle/BuildScanPublisher/help.html, src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy
=> Detect build scans in pipeline logs

src/main/java/hudson/plugins/gradle/BuildScanPublisher.java, src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy
Currently there is no way to retrieve the build scan URLs on post actions in order to send them to a chat application.
Before merging would love to know how to add a `BuildScanIntegrationTest` to verify my changes.
=> Return build scans list when calling findBuildScans()

.github/workflows/release-drafter.yml
GitHub Actions are enabled now, but they did not pick up the workflow definition automatically.
Looks like we need a commit to trigger the workflow creation.
=> Reference the Release Drafter docs from GitHub Actions

.github/workflows/release-drafter.yml
Going nuclear by trying a boilerplate fork of Release Drafter for GitHub Actions. https://github.com/oleg-nenashev/jenkins-release-drafter once we are happy with the change, we can get it upstreamed
https://github.com/toolmantim/release-drafter/issues/301
=> Apply workaround for issue #301 in Release Drafter

build.gradle, src/main/java/hudson/plugins/gradle/GradleInstallation.java
Note that the dependencies still need to be specified in `jenkinsPlugins`,
since the jpi plugin pulls the version from the dependency declaration,
not from the actual resolved dependency.
See https://github.com/jenkinsci/gradle-jpi-plugin/blob/bfcb36d38d7dc22fe72d1c4c64849890f75344f2/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifest.groovy#L149-L161
=> Use bom for pipeline dependencies

build.gradle
see https://github.com/gradle/test-retry-gradle-plugin
On ci.jenkins.io some tests are flaky. They sometimes run into a timeout when connecting to remote systems.
Question: Should the retry mechanism only be enabled on CI?
At least for Maven based plugins it is always enabled - see [here](https://github.com/jenkinsci/plugin-pom/blob/plugin-3.55/pom.xml#L1128-L1138).
If have no idea how disabling this mechanism can be implemented when only specific tests are run (as it is implemented for Maven plugins).
=> Use the "test-retry" plugin to handle flaky tests

src/main/java/hudson/plugins/gradle/GradleInstallation.java
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.
=> Do not try to serialize GradleInstallation over Remoting

src/main/java/hudson/plugins/gradle/BuildScanLogScanner.java, src/main/java/hudson/plugins/gradle/GradleConsoleAnnotator.java
In some cases, like when a few plugins are applied, the line length of the build scan published message can get large. In that case, the build scan URL has not been detected.
This PR removes the line length limit completely. The performance impact of scanning very long lines should be small, given that the full line already has been read into memory.
=> Remove line length limit for build scan message

src/main/java/hudson/plugins/gradle/Gradle.java
Resolve variables for **buildFile** in **getPossibleWrapperLocations** method (same as in **Gradle.perform** method)
Now it is not possible to calculate gradle wrapper location if **buildFile** contains env variables.
=> Support variables in build file location

build.gradle
See https://github.com/jenkinsci/gradle-jpi-plugin/issues/190 why the changes to `testRuntimeOnly` are necessary.
=> Upgrade jpi plugin to 0.43.0

README.adoc, build.gradle, src/main/java/hudson/plugins/gradle/injection/BuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/BuildScanInjectionListener.java, src/main/java/hudson/plugins/gradle/injection/ClearMavenOpts.java, src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/SetMavenOpts.java, src/main/resources/scripts/init-script.gradle, src/test/groovy/hudson/plugins/gradle/JavaGitContainer.java, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy, src/test/resources/hudson/plugins/gradle/JavaGitContainer/Dockerfile
Add the ability to enable Build Scans for both Gradle and Maven builds without having to change any pipeline. The feature is enabled by setting specific environment variables, see README.adoc for more information.
=> Allow Build Scan publishing without changing project configurations

src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
Use try-with-resource to make sure the InputStream is always closed.
=> Fix resource leak

Jenkinsfile, settings.gradle
This PR changes the Java version requirement for the project from 8 to 11. This change is required by the follow-up PRs.
=> Require Java 11 to build the plugin

src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java, src/test/groovy/hudson/plugins/gradle/injection/BaseInjectionIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/InjectionUtilsTest.groovy
[createOnlineSlave](https://github.com/c00ler/gradle-plugin/blob/5aefdb8129c91d177623085b621ed37b3689ef17/src/test/groovy/hudson/plugins/gradle/injection/BaseInjectionIntegrationTest.groovy#L18) sets the environment for the java command used to run the slave jar in the process builder. This is not an expected use-case so we replaced it with setting global env vars and also removed an unnecessary check.
=> Fix test environment setup and remove unnecessary JVM environment check.

src/main/java/hudson/plugins/gradle/injection/BuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/CopyUtil.java, src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java, src/main/java/hudson/plugins/gradle/injection/MavenOptsSetter.java, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsHandlerTest.groovy
This pull requests improves the performance of build scans injection by checking if required artifacts are already present. The check is done by comparing the files checksums. Such checks ensure that after the release of a new version of the plugin, the artifacts, if they were changed, will be updated. 
When setting `MAVEN_OPTS` the plugin is not creating a new `EnvironmentVariablesNodeProperty` every time but reuses an already existing one.
=> Inject resources only if they have changed

config/codenarc/codenarc.xml, src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
This pull request configures the  `codenarc` rule to ensure that static imports in the Groovy sources come after the nonstatic imports. It makes it consistent with the Java sources.
=> Align static imports order between groovy and java sources

acceptance-tests/build.gradle, build.gradle
Hi 
I'm not sure why this change was made other than it was in commit [`07a9c1d` (#185)](https://github.com/jenkinsci/gradle-plugin/pull/185/commits/07a9c1df5975955b5c39dc74adb190839d41b034)
This breaks:
* Installing the Gradle plugin via the Acceptance Test Harness, see https://github.com/jenkinsci/acceptance-test-harness/issues/985
* Adding this plugin as a dependency to another plugin and running it with `mvn hpi:run`
It would be appreciated if a quick release could be done so we can have the acceptance tests passing again, if it was just the gradle plugin failing we would skip the tests but it also prevents any plugins working that depend on the gradle plugin...
=> Revert jpi ext change

build.gradle.kts, src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java
Generate a class with the embedded extensions versions instead of a property file. Using a class makes a code simpler because versions are defined at compile time and there is no need to load them at runtime.
=> Generate a class containing the embedded extensions versions

src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/summary.jelly
`Build Tool Version` instead of `Built Tool Version`
=> Fix typo in Enriched job summary table

acceptance-tests/build.gradle.kts, build-logic/src/main/kotlin/buildlogic.chromedriver.gradle.kts
Automatically download chrome driver when running acceptance tests on CI.
=> Automatically download chrome driver when running on CI

gradle/wrapper/gradle-wrapper.properties
Bump up gradle to version `8.0.2`
=> Bump up gradle to version 8.0.2

build.gradle.kts, src/main/java/hudson/plugins/gradle/injection/EnvUtil.java, src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/MavenOptsSetter.java, src/main/java/hudson/plugins/gradle/injection/SystemProperty.java, src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
This pull request introduces the following changes:
* When maven auto-injection is disabled, update `MAVEN_OPTS` only if it has the changes added by auto-injection
* When maven auto-injection is disabled, remove `MAVEN_OPTS` instead of setting an empty value
* When maven auto-injection is enabled, merge changes with existing `MAVEN_OPTS` defined in the node properties. 
Fixes https://issues.jenkins.io/browse/JENKINS-70663 and https://issues.jenkins.io/browse/JENKINS-70692
=> Do not set empty MAVEN_OPTS environment variable

.github/dependabot.yml
Do not update `maven-core`, as we want to have full control over the used version.
=> Configure depandabot to ignore maven-core versions update

src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/enriched-css.jelly
fixes https://issues.jenkins.io/browse/JENKINS-70836
There is an option to always show scroll bars on MacOS:
With this enabled, the summary page starts showing useless scrollbars:
To fix this, the `overflow` parameter should be set to `auto` as described in the [documentation](https://www.w3schools.com/css/css_overflow.asp#:~:text=By%20default%2C%20the%20overflow%20is,content%20overflows%20an%20element's%20box.):
=> Set overflow to auto to display scrollbar only when necessary

build-logic/src/main/kotlin/buildlogic.chromedriver.gradle.kts, src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
`GradleEnterpriseExtensionsContributorFactory` is invoked on the master node and by constructing the `FilePath` object as we do now, the `exists` check returns `false`, since those files actually are located on the agent `Node` (in case job is executed on an agent). This led to the fact that injection didn't work when maven-plugin is used and job was scheduled on a remote agent (works fine for built-in node and agents being on the same node as master)
This fix creates `FilePath` properly and the `exists` check now verifies its existence on the agent node instead of master one.
This has been tested manually using the docker setup. We would need to come up with a different test setup as well, since our current one uses either built-in node or agent being on the same filesystem.
=> Fix the exist check of jar paths for maven-plugin

acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java, src/main/java/hudson/plugins/gradle/AbstractLogger.java, src/main/java/hudson/plugins/gradle/GradleEnterpriseLogger.java, src/main/java/hudson/plugins/gradle/GradleLogger.java, src/main/java/hudson/plugins/gradle/injection/BuildScanEnvironmentContributor.java, src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanEnvironmentContributorTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
Ensure Gradle Enterprise access key is not shown in plain text when [Environment Injector](https://plugins.jenkins.io/envinject/) plugin is used.
=> Ensure Gradle Enterprise access key is not shown in a plain text

src/main/resources/hudson/plugins/gradle/GradleTaskNote/script.js
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. I tested a very similar change successfully in the context of https://github.com/jenkinsci/ant-plugin/pull/121.
=> Replace Prototype.js with native JavaScript

src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseExceptionTaskListenerDecoratorFactory.java, src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleWithDurableTaskStepUseWatchingIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/GradleSnippets.groovy
This should fix https://issues.jenkins.io/browse/JENKINS-71509
Although this fixes the credentials masking when `org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep.USE_WATCHING` is set to true, the original `GradleEnterpriseExceptionTaskListenerDecorator` does not work in this case. It does not "see" all the log lines, it will require more investigation.
Provided integration tests
Manual tested on a local instance with the OpenTelemetry plugin (it sets `org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep.USE_WATCHING` to true) that secrets are masked on:
- Simple pipeline build with credentials binding plugin
- Simple pipeline build with Hashicorp Vault plugin
- Simple freestyle build with Hashicorp Vault plugin
```[tasklist]
```
=> Fix credentials not masked when `DurableTaskStep.USE_WATCHING` is true

src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseExceptionLogFilter.java, src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseExceptionLogProcessor.java, src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseExceptionTaskListenerDecoratorFactory.java, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleWithDurableTaskStepUseWatchingIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/GradleSnippets.groovy
Amends #312 by @alextu. While that appears to have worked, the _way_ in which it worked was not reassuring—an exception is still thrown, but it gets caught and does not break `withCredentials` masking. Better to avoid the exception to begin with. https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/323 proposes to enable `USE_WATCHING` by default, in which case the scenario would apply to all `gradle` plugin users, not only those who are also running `opentelemetry`.
Running
```bash
git checkout gradle-2.8 -- src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseExceptionTaskListenerDecoratorFactory.java
./gradlew -i :test --tests hudson.plugins.gradle.injection.BuildScanInjectionGradleWithDurableTaskStepUseWatchingIntegrationTest."credentials are always masked in …
```
=> [JENKINS-71509] Clean up of `GradleEnterpriseExceptionTaskListenerDecorator`

src/main/resources/hudson/plugins/gradle/injection/init-script.gradle
In order for the Gradle Enterprise plugin to deactivate any potentially build-changing features (at the time of writing that means all of its testing features) when applied via the init script rather than directly in the build, the `gradle.enterprise.externally-applied` system property is now set before applying it and reset afterwards.
via Gradle's [`BuildScanPluginSmokeTest`](https://github.com/gradle/gradle/blob/58f73541b54f0dfdb5c04b0c9e4666e88a6b8594/subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy) (PR pending)
```[tasklist]
```
=> Set `gradle.enterprise.externally-applied` before applying GE plugin

src/main/java/hudson/plugins/gradle/GradleConsoleAnnotator.java, src/main/java/hudson/plugins/gradle/GradleOutcomeNote.java, src/main/java/hudson/plugins/gradle/GradleTaskNote.java, src/main/java/hudson/plugins/gradle/TimestampPrefixDetector.java, src/test/groovy/hudson/plugins/gradle/GradleConsoleAnnotatorIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/GradleTaskNoteTest.groovy, src/test/groovy/hudson/plugins/gradle/TimestampPrefixDetectorTest.groovy
Fixes [JENKINS-72411](https://issues.jenkins.io/browse/JENKINS-72411) by detecting the timestamp prefix and shift the Gradle notes.
It should always be a complete timestamp and its format should not change (afaik it's changed by a formatter later on when displaying the console).
- Unit test for detecting the timestamp prefix
- Integration test to check the expected Gradle notes. The left menu could not be part of this test as it's loaded separately with an ajax request. I checked it manually though.
```[tasklist]
```
=> Fix GradleConsoleAnnotator when Timestamper is globally enabled

settings.gradle.kts
This prevents an error trying to push to the remote build cache from pull request forks which disables remote caching for the rest of the build.
This change is tested by using this pull request fork. There should be no build caching errors present in the logs.
```[tasklist]
```
=> Only push to remote build cache when access key is present

acceptance-tests/build.gradle.kts
Looks like download URLs are broken, switched to working ones in this PR.
```[tasklist]
```
=> Fix Jenkins war download URLs

src/main/resources/hudson/plugins/gradle/injection/init-script.gradle, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
Our current Gradle init script used for DV injection outputs some log messages in a high log level, meaning they are always present, even in Gradle quiet mode (cf https://docs.gradle.org/current/userguide/logging.html).
This PR will cause those messages to be hidden now in quiet mode.
Created an integration test for it, will also test it manually.
```[tasklist]
```
=> Change messages log level in init script

src/main/java/hudson/plugins/gradle/injection/GitScmListener.java, src/main/java/hudson/plugins/gradle/injection/MavenCoordinates.java, src/main/java/hudson/plugins/gradle/injection/MavenExtensions.java, src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleWithDurableTaskStepUseWatchingIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenCrossVersionTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsTest.groovy
If a project already has Develocity Maven extension applied, we shouldn't override it with our injection.
If Develocity Maven extension injection is enabled, we will check the `.mvn/extensions.xml` after checkout for the presence of said extension and disable the injection.
=> Apply Develocity Maven extension only if not already applied

src/main/java/hudson/plugins/gradle/injection/GitScmListener.java, src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java, src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java, src/main/java/hudson/plugins/gradle/injection/MavenCoordinates.java, src/main/java/hudson/plugins/gradle/injection/MavenExtClasspathUtils.java, src/main/java/hudson/plugins/gradle/injection/MavenExtension.java, src/main/java/hudson/plugins/gradle/injection/MavenExtensions.java, src/main/java/hudson/plugins/gradle/injection/MavenExtensionsDetector.java, src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java, src/main/java/hudson/plugins/gradle/injection/MavenOptsDevelocityFilter.java, src/main/java/hudson/plugins/gradle/injection/SystemProperty.java, src/main/resources/hudson/plugins/gradle/Messages.properties, src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/config.jelly, src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-ccudExtensionCustomCoordinates.html, src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-mavenExtensionCustomCoordinates.html, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenCoordinatesTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsDetectorTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsHandlerTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenOptsDevelocityFilterTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/SystemPropertyTest.groovy
Follow up of https://github.com/jenkinsci/gradle-plugin/pull/393
This PR adds 2 new fields to the Develocity Maven injection:
Those are used in case built projects have defined custom Develocity derived extensions:
- If the user specifies a GAV in "Develocity Maven Extension Custom Coordinates" field, the Develocity injection will be disabled if a corresponding extension is found in `.mvn/extensions` of the currently built project.
- Similarly, if the user specifies a GAV in "Common Custom User Data Maven Extension Custom Coordinates" field, the CCUD injection will be disabled if a corresponding extension is found in `.mvn/extensions` of the currently built project.
It's a bit complex in terms of implementation since we need to parse the existing `MAVEN_OPTS` looking for the maven ext …
=> Disable injection when custom extensions are detected

src/main/resources/hudson/plugins/gradle/injection/init-script.gradle, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
This PR fixes the task input files capturing for Gradle 5.x in afterevaluate block when enforce URL option is chosen (we simply move it out of that block)
=> Fix task input files capturing for Gradle 5.x in afterevaluate

build.gradle.kts
Hi! This updates the plugin to depend on the api-plugin versions of okhttp and jackson. This is a [recommended approach](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#using-library-wrapper-plugins) to code sharing.
I have a few plugins that depend on `gradle` and `okhttp-api`. I'm currently pinning back to Gradle 2.11 because 2.12 brings in its own copy of okhttp (https://github.com/jenkinsci/gradle-plugin/pull/426), causing runtime errors on startup.
While `okhttp-api` alone would fix the problem for me, I included jackson2 because it has the same guidance.
Thanks for taking a look!
Existing tests pass after the change.
=> Use Library Plugins for okhttp, jackson

acceptance-tests/build.gradle.kts, acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java, build.gradle.kts, settings.gradle.kts, src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy
This PR updates various versions:
- Latest Jenkins requires Java 17 or above
- Recently added plugin dependencies (jackson) require Jenkins 2.401.3 and Jenkins 2.401.3 requires Java 11 or above.
- Animal Sniffer is unnecessary with Java 11, replaced by compileJava `options.release = 11`
- Test harness is upgraded to fix some tests failures
=> Update Jenkins min version and adapt build

src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
Once migration is finished, we need to persist the data such that it's not done again
=> Save the configuration after migration is done

src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
The Gradle daemon of the build process was killed when using Gradle 8.10.1.
This fix is supposed to kill only Gradle daemon processes spawned during Jenkins builds.
=> Fix Gradle daemon cleanup on Windows

build.gradle.kts, src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java, src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigWithCasCTest.groovy, src/test/resources/injection-config.yml
https://issues.jenkins.io/browse/JENKINS-73843
`injectMavenExtension` and `injectCcudExtension` have been removed in 2.13. It causes a warning in Jenkins admin UI after upgrading, it causes a hard failure if using the Jenkins configuration-as-code plugin with a yaml configuration referencing those removed attributes.
This PR just keeps those attributes as transient, till the end of times I guess.
- Integration test
- Manually tested the upgrade with a pre-configured JCasC YAML referencing `injectMavenExtension` and `injectCcudExtension`.
=> Fix failure with configuration-as-code plugin when upgrading

acceptance-tests/build.gradle.kts, build.gradle.kts, src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/GradleInstallationRule.groovy, src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/DevelocityExceptionLogProcessorTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy, src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsDetectorTest.groovy
This PR addresses several things:
1. Acceptance tests on CI are fixed by bumping the base Jenkins version to 2.440.3
2. Running Acceptance tests with Latest Jenkins version is fixed (instead of running only with Latest LTS)
3. Adjusting other tests accordingly after bump to 2.440.3
=> Fix Acceptance tests

src/main/java/hudson/plugins/gradle/injection/BuildScanEnvironmentContributor.java, src/test/groovy/hudson/plugins/gradle/injection/BuildScanEnvironmentContributorTest.groovy
If Develocity injection is disabled, we don't want to have builds set with irrelevant password parameters.
- Unit test
- Manually tested that it works fine
=> Do not set password parameters if DV injection is disabled

src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy
The init script takes care of adapting the plugin version to old Gradle version.
=> Do not configure old DV plugin version in tests

src/main/java/hudson/plugins/gradle/injection/BuildScanEnvironmentContributor.java, src/main/java/hudson/plugins/gradle/injection/token/ShortLivedTokenClient.java, src/test/groovy/hudson/plugins/gradle/injection/token/ShortLivedTokenClientTest.groovy
If a user allows a build scan to be published to an untrusted server (can be enabled in the Develocity Injection configuration via UI), this PR makes sure to ignore any SSL errors when we resolve a short-lived token from that server.
=> Ignore SSL errors for short lived token request if allowUntrusted

src/main/java/hudson/plugins/gradle/injection/BuildScanEnvironmentContributor.java, src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/config.jelly, src/test/groovy/hudson/plugins/gradle/injection/BuildScanEnvironmentContributorTest.groovy
This change allows short-lived tokens creation even if Develocity Injection is disabled.
The UI has been adjusted to highlight configuration separation.
=> Create short-lived tokens if Develocity injection is disabled

src/main/java/hudson/plugins/gradle/injection/BuildScanEnvironmentContributor.java, src/main/java/hudson/plugins/gradle/injection/token/ShortLivedTokenClientFactory.java, src/test/groovy/hudson/plugins/gradle/injection/BuildScanEnvironmentContributorTest.groovy
Since `allowUntrusted` can be changed at runtime and it's unclear how Jenkins may manage the lifecycle of EnvironmentContributor, it's safer to just create a new instance of the client every time we need it (performance wise this is fine, as the token is requested once per build)
=> Take into account allowUntrusted when changed at runtime

.github/renovate.json
Configure Renovate to not execute Gradle wrapper/scripts updates.
Ran Renovate locally and see that it does not fail.
=> Disable Gradle udpates with Renovate

acceptance-tests/src/test/java/hudson/plugins/gradle/GradleEnterpriseErrorsTest.java, plugin/src/main/java/hudson/plugins/gradle/injection/DevelocityErrorsAction.java
The UX is different on 2.519: the Develocity button is only shown in the "hamburger" menu and not on the left menu:
We wait for confirmation it's final before adapting this test or not.
See [comment](https://issues.jenkins.io/browse/JENKINS-75727?focusedId=455604&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-455604).
In the meantime the test should not run on this version, as it consistently fails.
=> Ignore checkForGradleEnterpriseErrors test for Jenkins versions >= 2.519

plugin/pom.xml, plugin/src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy, plugin/src/test/groovy/hudson/plugins/gradle/BaseJenkinsIntegrationTest.groovy, plugin/src/test/groovy/hudson/plugins/gradle/BaseMavenIntegrationTest.groovy, plugin/src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy, plugin/src/test/groovy/hudson/plugins/gradle/GradleInstallationRule.groovy, plugin/src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy, plugin/src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy, plugin/src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleWithDurableTaskStepUseWatchingIntegrationTest.groovy
Fix Windows flaky integration tests:
- Do not execute Gradle integ test in parallel
- Use --no-daemon
- Kill any Gradle daemon after each Gradle integ test
The last step is kind of a catch-all thing, as the latest build logs show that only `captures build agent errors in pipeline build if checking for errors is enabled` seems to have a Gradle daemon leftover.
Ran the integration tests several times on Windows.
=> Fix flaky tests on Windows
