README.md
src/main/java/hudson/plugins/gradle/Gradle.java
src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy

This removes the large and quite difficult to use Constructor.

Use DataBoundSetter

---

build.gradle

[JENKINS-40004](https://issues.jenkins-ci.org/browse/JENKINS-40004)
@reviewbybees @wolfs

[JENKINS-40004] Add plugin description to POM

---

README.md
src/main/java/hudson/plugins/gradle/Gradle.java
src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy

Escaping done by `addKeyValuePairs` is already enough.
[FIXED JENKINS-42573]

Drop custom parameter escaping

---

src/main/java/hudson/plugins/gradle/GradleConsoleAnnotator.java
src/main/java/hudson/plugins/gradle/GradleOutcomeNote.java
src/main/java/hudson/plugins/gradle/GradleTaskNote.java

When using gradle 4.7 in jenkins, the outline does not work

Support annotate gradle 4.7 or later

---

README.md
build.gradle
src/main/java/hudson/plugins/gradle/Gradle.java

The plugin does not seem to be maintained any more and pulls in some
very old dependencies.

Remove support for dry run plugin

---

.github/release-drafter.yml

Just tried to check whether it is an encoding issue, does not look so

Reference the master doc in the Release Drafter configuration

---

src/main/resources/hudson/plugins/gradle/Gradle/help-rootBuildScriptDir.html

This resolve the issue [JENKINS-38479]
https://issues.jenkins-ci.org/browse/JENKINS-38479

Fix documentation of "Root Build script" [JENKINS-38479]

---

build.gradle

To see the new plugin in action and find bugs.

Use jpi plugin 0.39.0

---

src/main/resources/scripts/init-script.gradle

Those are necessary for the Teamcity plugin, not for the Jenkins plugin

Remove from init-script.gradle specific logging

---

build.gradle
src/main/java/hudson/FilePathUtil.java
src/main/java/hudson/plugins/gradle/injection/BuildScanInjectionListener.java
src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java
src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy

fix jenkinsci/gradle-plugin/pull/156

Do not log injection related error if feature is disabled

---

build.gradle
spotbugs-exclude.xml
src/main/java/hudson/plugins/gradle/BuildScanFlowAction.java
src/main/java/hudson/plugins/gradle/GradleConsoleAnnotator.java
src/main/java/hudson/plugins/gradle/GradleTaskListenerDecorator.java

This PR updates spotbugs to the latest version. After the upgrade spotbugs can work together with the new Gradle version.

Use the latest version of Gradle Spotbugs Plugin

---

build.gradle
src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/CliIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/ConfigurationAsCodeTest.groovy
src/test/groovy/hudson/plugins/gradle/GradleAbstractIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/MavenInstallationRule.groovy
src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BaseGradleInjectionIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenCrossVersionTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/MavenSnippets.groovy

Run injection tests with multiple Maven versions.

Run cross version tests for Maven

---

README.adoc
src/main/resources/hudson/plugins/gradle/BuildScanPublisher/help.html
src/main/resources/hudson/plugins/gradle/Messages.properties
src/main/resources/hudson/plugins/gradle/Messages_de.properties

Improve documentation

---

RELEASING.md

Add a new release step, to update the compatibility matrix with the new version + improve the formatting

Update compatibility matrix during the release

---

README.adoc

Fix the roadmap section in the README

Fix roadmap section in the README

---

acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java
build.gradle
configuration-maven-extension/build.gradle
configuration-maven-extension/src/main/java/com/gradle/jenkins/maven/extension/internal/GradleEnterpriseConfigurerListener.java
configuration-maven-extension/src/main/resources/META-INF/plexus/components.xml
settings.gradle
src/main/java/hudson/plugins/gradle/injection/EnvUtil.java
src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java
src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java
src/main/java/hudson/plugins/gradle/injection/MavenOptsSetter.java
src/main/java/hudson/plugins/gradle/injection/SystemProperty.java
src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
src/test/groovy/hudson/plugins/gradle/CliIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/CompatibilityTest.groovy
src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy

This pull request adds Build Scans auto-injection support for the jobs using `maven-plugin`. The minimum required version of `maven-plugin` is `3.20`

Build Scans auto-injection support for maven-plugin

---

acceptance-tests/build.gradle
acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java

Update acceptance test harness version

Bump up acceptance test harness version

---

src/main/java/hudson/plugins/gradle/BuildScanLogScanner.java
src/test/groovy/hudson/plugins/gradle/BuildScanLogScannerTest.groovy

Fixes https://issues.jenkins.io/browse/JENKINS-69934

Improve build scan link capturing

---

README.adoc
acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java
settings.gradle

Upgrade bundled Gradle Enterprise Maven extension version to `1.16`.

Upgrade bundled Gradle Enterprise Maven extension version.

---

acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
acceptance-tests/src/test/java/hudson/plugins/gradle/MockGeServer.java
src/main/resources/hudson/plugins/gradle/injection/init-script.gradle

Disable upload in the background for Gradle.

Disable upload in background for Gradle

---

build.gradle

Update `gradle-jpi-plugin` version.

Bump gradle-jpi-plugin version

---

README.adoc
acceptance-tests/build.gradle
settings.gradle

Fix compatibility with the nightly jenkins version.

Update acceptance test harness version

---

README.adoc
settings.gradle.kts

Updates embedded maven extension version to `1.16.3`

Upgrade embedded maven extension version

---

README.adoc
settings.gradle.kts

Upgrade embedded GE maven extension version to 1.16.4

Upgrade embedded GE maven extension version to 1.16.4

---

README.adoc
settings.gradle.kts

Upgrade embedded GE maven extension version to 1.16.6

Upgrade embedded GE maven extension version to 1.16.6

---

acceptance-tests/src/main/java/hudson/plugin/gradle/BuildScansInjectionSettings.java
acceptance-tests/src/test/java/hudson/plugins/gradle/AbstractAcceptanceTest.java
src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseAccessKeyValidator.java
src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java

Do not use commons-lang3 as it is not available without the `maven-plugin`, that is optional.

Do not use commons-lang3 when it is not available

---

settings.gradle.kts

Bump CCUD Maven extension to 1.12

Bump CCUD Maven extension to 1.12

---

settings.gradle.kts

Bump GE Maven extension to 1.17.3

Bump GE Maven extension to 1.17.3

---

settings.gradle.kts

Bump CCUD Maven extension to 1.12.1
```[tasklist]
```

Bump CCUD Maven extension to 1.12.1

---

README.adoc
settings.gradle.kts

Bump to latest GE components

---

README.adoc
settings.gradle.kts

Update Gradle Enterprise Maven extension 1.18.1

---

acceptance-tests/build.gradle.kts
build-logic/src/main/kotlin/buildlogic.chromedriver.gradle.kts

Updates the version of acceptance test harness
```[tasklist]
```

Bump org.jenkins-ci:acceptance-test-harness from 5581.vfd8e43f46a_03 to 5668.vddb_c1150ef3d

---

build-logic/src/main/kotlin/buildlogic.chromedriver.gradle.kts

Update chrome driver to `116.0.5845.96`
```[tasklist]
```

Update Chrome driver to 116.0.5845.96

---

README.adoc
settings.gradle.kts

Updated Gradle Enterprise Maven Extension to 1.19
Project builds.
```[tasklist]
```

Updated Gradle Enterprise Maven Extension to 1.19

---

README.adoc
settings.gradle.kts

Bumped Gradle Enterprise Maven Extension to 1.19.1
Project builds.
```[tasklist]
```

Bumped Gradle Enterprise Maven Extension to 1.19.1

---

README.adoc
settings.gradle.kts

Bump CCUD maven extension to 1.12.3
Project builds.
```[tasklist]
```

Bump CCUD maven extension to 1.12.3

---

settings.gradle.kts

Adds a Gradle Enterprise project ID to the build.
I ran `./gradlew build` and verified the tests passed. Since this is a build change, additional changes should not be required.
```[tasklist]
```

Add a Gradle Enterprise Project ID to the build

---

build-logic/src/main/kotlin/buildlogic.chromedriver.gradle.kts

Updates the chromedriver version to 119.0.6045.105

Update chromedriver to 119.0.6045.105

---

README.adoc
settings.gradle.kts

Update DV Maven extension 1.20
```[tasklist]
```

Update DV Maven extension 1.20

---

README.adoc
settings.gradle.kts

Bump CCUD Maven 1.13

---

src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy

Follow up of https://github.com/jenkinsci/gradle-plugin/pull/398
The `custom-extension` branch has been merged to the original sample project we use, this PR just changes it so we don't use various sample projects.
```[tasklist]
```

Use original sample Maven project

---

src/test/groovy/hudson/plugins/gradle/injection/MavenSnippets.groovy

This is best to disable background upload when running on CI: if enabled, some temp files might be left in `$HOME/.m2/.gradle-enterprise`.
```[tasklist]
```

Disable background upload on a test

---

build.gradle.kts
configuration-maven-extension/build.gradle.kts
settings.gradle.kts
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy

Upgrade the embedded CCUD Maven extension to 2.0
```[tasklist]
```

Upgrade CCUD Maven extension to 2.0

---

src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy

This PR removes the output of whole environment during test jobs and prints only necessary variables for assertions

Print only necessary variables for assertions

---

README.adoc

n/a - readme change only
```[tasklist]
```

Update compatibility table for new Extension versions with 2024.1

---

README.adoc
settings.gradle.kts

Bump com.gradle:develocity-maven-extension to 1.21.1
```[tasklist]
```

Bump com.gradle:develocity-maven-extension to 1.21.1

---

src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy

Bump com.gradle:develocity-gradle-plugin to 3.17.1 in test
```[tasklist]
```

Bump com.gradle:develocity-gradle-plugin to 3.17.1

---

src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java
src/main/java/hudson/plugins/gradle/injection/InitScriptVariables.java
src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy

It was set to true by default only in the UI, not in the "domain"
```[tasklist]
```

Set default file fingerprinting to true

---

README.adoc
settings.gradle.kts

Update to Develocity Maven Extension 1.21.2

---

README.adoc
settings.gradle.kts

Bump com.gradle:develocity-maven-extension from 1.21.2 to 1.21.3

---

README.adoc

Notes regarding the Develocity 2024.1 requirement. Follow up of https://github.com/jenkinsci/gradle-plugin/pull/426
```[tasklist]
```

Add notes to README regarding short-lived tokens

---

src/main/resources/hudson/plugins/gradle/injection/init-script.gradle

Updates the develocity-injection init script to the latest reference script content
from https://github.com/gradle/develocity-ci-injection.

Update develocity-injection init script to v1.0

---

acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java

Ignore autoInjectionSkippedWhenOldMavenPlugin because it sometimes fails to install `maven-plugin` plugin

Ignore `autoInjectionSkippedWhenOldMavenPlugin`

---

README.adoc

Rephrases the build scan links detection.

Fix README regarding Build Scan publication

---

build.gradle.kts

see https://github.com/jenkinsci/plugin-pom/pull/415
Compiled locally

Use latest jpi plugin to compile with -parameters

---

acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java

Follow up of https://github.com/jenkinsci/gradle-plugin/pull/540
Env var has been renamed.

Fix `gradlePluginRepoPasswordIsMasked` acceptance test

---

.github/renovate.json

First renovate configuration to update latest and latest-lts hardcoded versions.
Could not test this, will need to tweak it probably after this first merge.

Try renovate to update latest and latest-lts

---

acceptance-tests/src/test/java/hudson/plugins/gradle/AbstractAcceptanceTest.java
acceptance-tests/src/test/java/hudson/plugins/gradle/GradleEnterpriseErrorsTest.java
acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
acceptance-tests/src/test/java/hudson/plugins/gradle/MavenEnrichedScansTest.java
acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java
acceptance-tests/src/test/resources/mvn_extensions_with_ge.xml
acceptance-tests/src/test/resources/simple_maven_project/.mvn/develocity.xml
acceptance-tests/src/test/resources/simple_maven_project/.mvn/gradle-enterprise.xml
src/main/java/hudson/plugins/gradle/BuildScanLogScanner.java
src/test/groovy/hudson/plugins/gradle/BuildScanIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/BuildScanLogScannerTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenCrossVersionTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigWithCasCTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionDownloadHandlerTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsDetectorTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsHandlerTest.groovy
src/test/groovy/hudson/plugins/gradle/injection/MavenSnippets.groovy
src/test/resources/injection-config.yml

Adapt the build log parser to future changes in the Develocity Gradle plugin, Maven extension.

Adapt to next scan publishing log message

---

README.adoc

Fix images path in README

---

.github/workflows/gradle-wrapper-validation.yml

Update gradle-wrapper-validation to v4

---

plugin/pom.xml

Build currently fails with 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (display-info) on project gradle:
[ERROR] Rule 6: org.apache.maven.enforcer.rules.dependency.RequireUpperBoundDeps failed with message:
[ERROR] Failed while enforcing RequireUpperBoundDeps. The error(s) are [
[ERROR] Require upper bound dependencies error for com.google.guava:guava:33.3.0-jre [runtime] paths to dependency are:
[ERROR] +-io.jenkins.plugins:gradle:2.16.999999-SNAPSHOT
[ERROR]   +-com.gradle:configuration-maven-extension:1.0.0 [runtime]
[ERROR]     +-org.apache.maven:maven-core:3.9.10 [runtime]
[ERROR]       +-com.google.guava:guava:33.3.0-jre [runtime] (managed) <-- com.google.guava:guava:33.4.8-jre [runtime]
[ERROR] ]
```
after …

Fix version conflict on guava

---

acceptance-tests/pom.xml
acceptance-tests/src/test/java/hudson/plugins/gradle/AbstractAcceptanceTest.java
acceptance-tests/src/test/java/hudson/plugins/gradle/GradleEnrichedScansTest.java
acceptance-tests/src/test/resources/hudson.plugins.gradle.GradleInstaller
acceptance-tests/src/test/resources/simple_gradle_project_with_dv.groovy.template
plugin/src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/index.jelly
plugin/src/main/resources/hudson/plugins/gradle/BuildScanColumn/column.jelly

The "Pipeline Steps" view missed at some point the Gradle Build scan link if there was one (or many) detected.
- Add a functional test that checks the "Pipeline Steps" view
- Manual test

Add back the Build Scan link(s) in the Pipeline Steps view
